### ISSUE TITLE
Turner syndrome has no phenotypes

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/hpo-annotation-data#3]
neither the parent DO term http://tartini.crbs.ucsd.edu/disease/DOID:3491
nor the orphanet child term http://tartini.crbs.ucsd.edu/disease/Orphanet:99413

**Comment by pnrobinson** [comment]
Turner syndrome (the Orphanet ID) does have HPO annotations, see them in http://compbio.charite.de/phenexplorer/
There must be some issue with the ingest pipeline?
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universit�t Berlin
Institut f�r Medizinische Genetik und Humangenetik
Charit� - Universit�tsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________________
Von: Melissa Haendel [notifications@github.com]
Gesendet: Mittwoch, 27. Mai 2015 12:50
An: monarch-initiative/hpo-annotation-data
Betreff: [hpo-annotation-data] Turner syndrome has no phenotypes (#3)

neither the parent DO term http://tartini.crbs.ucsd.edu/disease/DOID:3491
nor the orphanet child term http://tartini.crbs.ucsd.edu/disease/Orphanet:99413

�

**Comment by mellybelly** [comment]
Indeed!

**Comment by cmungall** [comment]
OK, a few things going on here.

 1.There are a bunch of different Turner's we're talking about different ones.
 2. The monarch beta site is still driven by federation which we have not updated in a long time

Which Turner?

This is ORDO:

```
  po Orphanet:881 ! Turner syndrome <-- **WE HAVE ANNOTATIONS TO THIS **
   po Orphanet:99226 ! Monosomy X
   po Orphanet:99228 ! Mosaic monosomy X
   po Orphanet:99413 ! Turner syndrome due to structural X chromosome anomalies <-- ** WE HAVE NO ANNOTATIONS TO THIS**
```

so it's not surprising you see nothing to the child

the fact you don't see any to the parent probably reflects some federation issue we are not going to fix

You can query what we actually have:

http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/diseases/Orphanet:881/phenotypes.json

However, I'm not finding in golr which is an issue

Anyway, not a data issue







Orphanet:99413 ! Turner syndrome due to structural X chromosome anomalies


http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/diseases/Orphanet:881/phenotypes.json

**Comment by mellybelly** [comment]
yeah, I cannot seem to autocomplete on: Orphanet:881 ! Turner syndrome , only the DO term, which has no annotations.

**Comment by mellybelly** [comment]
still can't get to the orphanet page in monarch.
