### ISSUE TITLE
annotate OMIM content to genes to gene ID

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/hpo-annotation-data#4]
OMIM has phenotypic data annotated to both diseases and genes, we have asked that they address this and separate the two. In lieu of this fix, perhaps for our own annotations we should annotate to Entrez IDs instead of OMIM IDs for genes?

@nlwashington @cmungall working on some downstream fixes for the moment

**Comment by pnrobinson** [comment]
Some genes have multiple diseases, so using Entrez IDs would create new complications.
A typical problem we had recently was that OMIM is not always up to date, and thus there are some diseases that are not yet in OMIM. Being more specific, there is not always a lot of evidence for these diseases and OMIM requires at least two publications and reasonably good evidence to call something a new Mendelian disease.
We could solve some problems by annotating to OMIM gene entries (or Entrez Gene IDs) and keeping track of this fact in case the genes later get bumped up into "official" disease genes.
-P

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Melissa Haendel [notifications@github.com]
Gesendet: Dienstag, 21. Juli 2015 00:16
An: monarch-initiative/hpo-annotation-data
Betreff: [hpo-annotation-data] annotate OMIM content to genes to gene ID (#4)


OMIM has phenotypic data annotated to both diseases and genes, we have asked that they address this and separate the two. In lieu of this fix, perhaps for our own annotations we should annotate to Entrez IDs instead of OMIM IDs for genes?

@nlwashington<https://github.com/nlwashington> @cmungall<https://github.com/cmungall> working on some downstream fixes for the moment

**Comment by drseb** [comment]
IMHO this can be fixed downstream. we are trying to avoid annotating genes.
